# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc76d1394000fd2ed1982518c91febdece3ffb99d1e6ceee2197dd892b4eae85e92f1e80c3550a156092c17e0875f5d68a0f52d2ae065fdbad059713014b828b

test:
  secret_key_base: 0ea96fd4a1c8e23986252c5793fa90bf0b2fdbddec4062255a3bdf5d16bf4cf536577768423a7a867b0569b25cf30280a08c00f32d06f8546c655e23bb23b64e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
